### ISSUE TITLE
out-of-the-box, method missing

### ISSUE THREAD

**Issue by pmbauer** [alandipert/hoplon-contacts-demo#1]
![screenshot from 2015-08-07 17 17 46](https://cloud.githubusercontent.com/assets/453580/9146205/b7a539cc-3d28-11e5-8278-865509cc72ab.png)

**Comment by alandipert** [comment]
Thanks for the report!  This looks like https://github.com/boot-clj/boot/issues/266

Please download the latest boot.sh and lemme know if it works.

**Comment by pmbauer** [comment]
Explicitly downloading boot.sh did fix it. Thanks. I assume this was a one-time-thing and `boot -u` would normally work?

**Comment by alandipert** [comment]
Yeah the problem is that the new boot core (set of jars supporting 2.2.0) wasn't backward-compatible with 2.0.0 boot.sh.  boot -u was upgrading into broken boot support jars.  Another fix would have been to pin BOOT_VERSION to 2.1.2 in ~/.boot/boot.properties.

In the future we will test this scenario, and if possible, write boot core to be more backward-compatible.
